### ISSUE TITLE
Fix code.

### ISSUE THREAD

**Issue by JohnKun136NVCP** [1Jp1/calcumatrices#1]
https://github.com/1Jp1/calcumatrices/blob/0b6608e44d26ca19e2e4ed76b7ff3d96c592004f/matrices.cpp#L6
Principalmente dije sí con 2 matrices pero de tamaño de NxN, no de 2x2.

**Comment by 1Jp1** [comment]
Ya lo corregi jhon, me sirvio igual de practica para familiarizarme con git
